### ISSUE TITLE
suggestion- add vaccine name as param

### ISSUE THREAD

**Issue by anuj2rock** [abhinavdc/cowin-pinger#12]
please refer schema of official cowin api and lets parse out on "vaccine" object in response from cowin API and match it to user provided argument. that way user can give --vaccinename=covaxin (as an example.)

**Comment by abhinavdc** [comment]
That feature was in code review in PR https://github.com/abhinavdc/cowin-pinger/pull/10 and was just merged to main. I will updated the npm library with this new change soon.

**Comment by anuj2rock** [comment]
Ok I didn't check PR 10. Cool. Will do more code review and let you know.
