### ISSUE TITLE
Continue pinging even if slots are available

### ISSUE THREAD

**Issue by yashgorana** [abhinavdc/cowin-pinger#17]
Currently the script shuts down after a slot is found/notification is sent.
There's been multiple occasions where the notification was received but by the time we book on the portal, it's too late. I think we should continue running the script even when notification is sent.

We can keep this option OFF by default and enable it through a `--keep-alive` flag.

**Comment by abhinavdc** [comment]
That's a really good idea! Will add this feature.

**Comment by prayuj** [comment]
I will be happy to take this up!

**Comment by abhinavdc** [comment]
Awesome! Thanks @prayuj
