### ISSUE TITLE
Bug: 18+ slots are notified for age 45+

### ISSUE THREAD

**Issue by yashgorana** [abhinavdc/cowin-pinger#18]
The tool was run with the following configuration
> Date= 24-05-2021
> Age= 54
> Dose= First Dose
> Pincode= pin
> Time interval= 1 minutes (default is 10)
> Appointment Count= 2 (default is 2)
> IFTTT API Key= key
> IFTTT Hook Name= slot

The CoWIN portal does not allow the age of 45+ to get appointment for 18+ slots
Here's a screenshot of the error thrown from the CoWin portal.
![44](https://user-images.githubusercontent.com/11070218/119352204-eba98500-bc90-11eb-9d01-d20fdf058692.PNG)

Even though the age is configured as **54** when running the tool, it is notifying slots that are marked for 18-44 age group, which it should not.

**Comment by abhinavdc** [comment]
Thanks for pointing this out. Didn't know 18+ slots have a max age limit of 44. This issue has been fixed!
