### ISSUE TITLE
Add other vaccine to the list sputnik V

### ISSUE THREAD

**Issue by sahithkotagiri** [abhinavdc/cowin-pinger#20]
It would do good if you add sputnik V to the vaccine list since many states were procuring the vaccine.

**Comment by abhinavdc** [comment]
Thanks @sahithkotagiri , thank you for the suggestion. Will add this feature!

**Comment by aryanjha22** [comment]
#26

**Comment by aryanjha22** [comment]
#26 I have added the sputnik-v section to the list of vaccines.

**Comment by sahithkotagiri** [comment]
Can you tell me how to update the code i deleted the old file and downloaded new one but it still extracts the old one.

**Comment by abhinavdc** [comment]
@sahithkotagiri Download the latest version of the library and you'll be able to use the new filter for Sputnik. Let me know if you run into any issues.
