### ISSUE TITLE
stopping after 1 successfull ping 

### ISSUE THREAD

**Issue by MANWHOKNEWINFINITY** [abhinavdc/cowin-pinger#7]
the code stops after the first successful ping any reason why?

**Comment by MANWHOKNEWINFINITY** [comment]
yes, but I was getting slots on 16th and 17 when there were many slots available on earlier dates.

**Comment by abhinavdc** [comment]
I have added the feature to allow search for custom dates and it also uses today's date instead of next day's date in the request.
